package models

// SandboxConfig is the user-provided configuration for a sandbox session.
type SandboxConfig struct {
	Image        string          `yaml:"image" mapstructure:"image"`
	Workdir      string          `yaml:"workdir" mapstructure:"workdir"`
	Mounts       []MountConfig   `yaml:"mounts" mapstructure:"mounts"`
	Secrets      []SecretMapping `yaml:"secrets" mapstructure:"secrets"`
	ProxyPort    int             `yaml:"proxy_port" mapstructure:"proxy_port"`
	NoAutoMounts bool            `yaml:"-" mapstructure:"-"` // runtime flag, not persisted
}

// MountConfig describes an additional directory mount.
type MountConfig struct {
	Source string `yaml:"source" mapstructure:"source"`
	Target string `yaml:"target" mapstructure:"target"`
	Mode   string `yaml:"mode" mapstructure:"mode"` // "ro" or "rw", default "ro"
}

// SecretMapping defines an environment variable-based secret.
// The Env field specifies the host env var name. The real value is read from
// the host environment (or from an explicit Value override). Placeholder is
// auto-generated by ResolveEnvSecrets and used for proxy replacement.
type SecretMapping struct {
	Env         string   `yaml:"env" mapstructure:"env"`
	Value       string   `yaml:"value,omitempty" mapstructure:"value"`
	Placeholder string   `yaml:"-" mapstructure:"-"` // auto-generated, not persisted
	ReplaceIn   []string `yaml:"replace_in" mapstructure:"replace_in"` // "headers", "body", "query"
}

// ReplacementLocation constants.
const (
	ReplaceHeaders = "headers"
	ReplaceBody    = "body"
	ReplaceQuery   = "query"
)
